version: '3.9'

services:
  mongo:
    image: 'mongo'
    ports: 
      - 27017:27017

  zookeeper:
    image: confluentinc/cp-zookeeper
    restart: always
    ports:
      - 2181:2181
    environment: 
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEPER_TICK_TIME: 2000
  
  kafka:
    image: confluentinc/cp-kafka
    ports:
      - 9092:9092
    environment: 
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_BROKER_ID: 1

  kafka-setup:
    image: confluentinc/cp-kafka
    hostname: kafka-setup
    container_name: kafka-setup
    depends_on: 
      - kafka
      - zookeeper
    command: "bash -c 'echo Setting up Kafka... && \
                       cub kafka-ready -b kafka:9092 1 60 && \
                       kafka-topics --create --if-not-exists --zookeeper zookeeper:2181 --partitions 3 --replication-factor 1 --topic storytasks.dev'"
    environment: 
      KAFKA_BROKER_ID: ignored
      KAFKA_ZOOKEPER_CONNECT: ignored

  kafkahq:
    image: tchiotludo/kafkahq
    ports:
      - 8000:8080
    environment: 
      KAFKAHQ_CONFIGURATION: |
        kafkahq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: 'kafka:9092'
    links: 
      - kafka
