# Application Variables
vars:
  application:
    environment: ${APP_ENVIRONMENT:local}
    name: ${APP_NAME:story-tasks-api}
    version: ${APP_VERSION:1.0.0}
  mongodb:
    url: ${DATABASE_URL:mongodb://localhost:27017/story-tasks}
  server:
    port: ${PORT:8080}
  security:
    cors-allowed-origins: ${CORS_ALLOWED_ORIGINS:*}
    google-oauth2-client-id: ${GOOGLE_OAUTH2_CLIENT_ID}
    google-oauth2-client-secret: ${GOOGLE_OAUTH2_CLIENT_SECRET}

# Application Properties
server:
  port: ${vars.server.port}

spring:
  application:
    name: ${vars.application.name}
  data:
    mongodb:
      uri: ${vars.mongodb.url}
      auto-index-creation: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${vars.security.google-oauth2-client-id}
            client-secret: ${vars.security.google-oauth2-client-secret}
