
# Application Variables
vars:
  application:
    environment: ${APP_ENVIRONMENT:local}
    name: ${APP_NAME:story-tasks-api}
    version: ${APP_VERSION:1.0.0}
  mongodb:
    url: ${DATABASE_URL:mongodb://localhost:27017/story-tasks}
  server:
    port: ${PORT:8080}
  security:
    cors-allowed-origins: ${CORS_ALLOWED_ORIGINS:*}
    okta-oauth2-issuer: ${OKTA_OAUTH2_VAL_ISSUER}
    okta-oauth2-client-id: ${OKTA_OAUTH2_VAL_CLIENT_ID}
    okta-oauth2-client-secret: ${OKTA_OAUTH2_VAL_CLIENT_SECRET}


# Application Properties
server:
  port: ${vars.server.port}

okta:
  oauth2:
    issuer: ${vars.security.okta-oauth2-issuer}
    client-id: ${vars.security.okta-oauth2-client-id}
    client-secret: ${vars.security.okta-oauth2-client-secret}

spring:
  application:
    name: ${vars.application.name}
  data:
    mongodb:
      uri: ${vars.mongodb.url}
      auto-index-creation: true

management:
  endpoints:
    enabled-by-default: false
    web.base-path: "/"
  endpoint:
    health.enabled: true

logging:
  level:
    root: INFO
#    org.springframework.web: DEBUG
#    org.springframework.security: DEBUG
#    org.springframework.security.oauth2: DEBUG
#    org.springframework.web.client.RestTemplate: DEBUG